# ROUTING PARA CONSULTA AJAX (SEGUIR)
follow_follow:
  path: /follow
  defaults: { _controller: AppBundle:Follow:follow }
  methods: [POST]
  
# ROUTING PARA CONSULTA AJAX (DEJAR DE SEGUIR)
follow_unfollow:
  path: /unfollow
  defaults: { _controller: AppBundle:Follow:unfollow }
  methods: [POST]

follows_list_users:
  path: /follows/{nick}/{type}
  defaults: { _controller: AppBundle:Follow:followsList, nick: null, type: null }