AppBundle\Entity\Likes:
    type: entity
    table: sn_like
    indexes:
        like_user_fk:
            columns:
                - user
        like_publication_fk:
            columns:
                - publication
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
        publication:
            targetEntity: Publication
            cascade: [ persist ]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                publication:
                    referencedColumnName: id
                    onDelete: CASCADE
                    onUpdate: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
